### ISSUE TITLE
Temporary Directories for Test files

### ISSUE THREAD

**Issue by chebizarro** [valadate-project/valadate#15]
Valadate 0.1.1 had the following feature:
- Utility functions providing temporary directory to tests.
  
  With support for initializing the temporary directory by storing data, copying specified files there, and running a shell snippet.

**Comment by chebizarro** [comment]
These will need to be reviewed for Version 2.0 and possibly deprecated

**Comment by astavale** [comment]
GLib's GIO provides [File.new_tmp ()](https://valadoc.org/gio-2.0/GLib.File.new_tmp.html). This has worked well for me in the past. For example in Genie:

```
class AugeasShadowFixture
	tmp_file:string = ""

	_file:File
	_iostream:FileIOStream

	def set_up()
		try
			_file = File.new_tmp ("install_os_test-shadow-XXXXXX", out _iostream)
			tmp_file = _file.get_path ()
			ostream:OutputStream = _iostream.output_stream
			dostream:DataOutputStream = new DataOutputStream (ostream)
			dostream.put_string ("root:*:0:0:99999:7:::")
		except error:Error
			print error.message

	def tear_down()
		try
			_file.delete()
		except error:Error
			print error.message
```

The `tear_down ()` call could even be made automatic in Vala by making it a destructor.
