### ISSUE TITLE
autogen.sh failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by steveno** [valadate-project/valadate#24]
> **Warning**: I am going to run `configure' with no arguments.
> If you wish to pass any to it, please specify them on the
> `./autogen.sh' command line.
> 
> processing .
> Running libtoolize...
> libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build'.
> libtoolize: copying file 'build/ltmain.sh'
> libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build/autotools'.
> libtoolize: copying file 'build/autotools/libtool.m4'
> libtoolize: copying file 'build/autotools/ltoptions.m4'
> libtoolize: copying file 'build/autotools/ltsugar.m4'
> libtoolize: copying file 'build/autotools/ltversion.m4'
> libtoolize: copying file 'build/autotools/lt~obsolete.m4'
> Running aclocal  ...
> Running autoheader...
> Running automake --gnu  ...
> configure.ac:20: installing 'build/compile'
> configure.ac:16: installing 'build/missing'
> libvaladate/Makefile.am:108: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
> libvaladate/Makefile.am: installing 'build/depcomp'
> Running autoconf ...
> Running ./configure ...
> checking whether make supports nested variables... yes
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... no
> checking for mawk... mawk
> checking whether make sets $(MAKE)... yes
> checking whether to enable maintainer-specific portions of Makefiles... yes
> checking for style of include used by make... GNU
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... gcc3
> checking for ar... ar
> checking the archiver (ar) interface... ar
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.16... yes
> checking for GLIB - version >= 2.0.0... yes (version 2.48.1)
> checking for gcc... (cached) gcc
> checking whether we are using the GNU C compiler... (cached) yes
> checking whether gcc accepts -g... (cached) yes
> checking for gcc option to accept ISO C89... (cached) none needed
> checking whether gcc understands -c and -o together... (cached) yes
> checking dependency style of gcc... (cached) gcc3
> checking for valac... /usr/bin/valac
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking how to print strings... printf
> checking for a sed that does not truncate output... /bin/sed
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for fgrep... /bin/grep -F
> checking for ld used by gcc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572864
> checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
> checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... no
> checking how to associate runtime and link libraries... printf %s\n
> checking for archiver @FILE support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking command to parse /usr/bin/nm -B output from gcc object... ok
> checking for sysroot... no
> checking for a working dd... /bin/dd
> checking how to truncate binary pipes... /bin/dd bs=4096 count=1
> checking for mt... mt
> checking if mt is a manifest tool... no
> checking how to run the C preprocessor... gcc -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if gcc supports -fno-rtti -fno-exceptions... no
> checking for gcc option to produce PIC... -fPIC -DPIC
> checking if gcc PIC flag -fPIC -DPIC works... yes
> checking if gcc static flag -static works... yes
> checking if gcc supports -c -o file.o... yes
> checking if gcc supports -c -o file.o... (cached) yes
> checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> checking for VALADATE... yes
> checking for VALADATE_CLI... yes
> checking for TESTS... yes
> ./configure: line 14383: syntax error near unexpected token `1.38.0'
> ./configure: line 14383: `GOBJECT_INTROSPECTION_CHECK(1.38.0)'

**Comment by chebizarro** [comment]
Hi, this error normally means you need to install libgirepository-dev. Try that and let me know if you still get the error. I'll try and update the docs this week for more information on installing from source.

**Comment by steveno** [comment]
This was the command that fixed it:
`
apt-get install libgirepository1.0-dev
`

Thanks for the quick reply!!
