### ISSUE TITLE
Invalid signature for Debian repository

### ISSUE THREAD

**Issue by kostya-ripak** [valadate-project/valadate#44]
After adding your key, trying to update repository gives error:

sudo apt-get update
Get:1 file:/var/cuda-repo-9-0-local  InRelease
Ign:1 file:/var/cuda-repo-9-0-local  InRelease                                               
Get:2 file:/var/cuda-repo-9-0-local  Release [574 B]                                                           
Get:2 file:/var/cuda-repo-9-0-local  Release [574 B]                                                                                    
Hit:3 http://ru.archive.ubuntu.com/ubuntu zesty InRelease                                                                                                                                                         
Hit:4 http://ru.archive.ubuntu.com/ubuntu zesty-updates InRelease                                                                                                                                                 
Hit:5 http://ru.archive.ubuntu.com/ubuntu zesty-backports InRelease                                                                                                                                      
Ign:6 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                             
Hit:8 http://archive.ubuntu.com/ubuntu zesty InRelease                                                                                        
Hit:9 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu zesty InRelease                                          
Hit:10 http://security.ubuntu.com/ubuntu zesty-security InRelease                             
Hit:11 http://ppa.launchpad.net/linrunner/tlp/ubuntu zesty InRelease                                
Hit:12 https://repo.skype.com/deb stable InRelease                       
Hit:13 http://dl.google.com/linux/chrome/deb stable Release                                         
Hit:14 https://deb.opera.com/opera-stable stable InRelease                                          
Hit:15 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu zesty InRelease
Get:17 https://www.valadate.org/repos/debian valadate InRelease [3 842 B]
Ign:17 https://www.valadate.org/repos/debian valadate InRelease
Get:18 https://www.valadate.org/repos/debian valadate/main amd64 Packages [643 B]
Get:19 https://www.valadate.org/repos/debian valadate/main i386 Packages [644 B]
Fetched 5 129 B in 1s (3 479 B/s) 
Reading package lists... Done
W: GPG error: https://www.valadate.org/repos/debian valadate InRelease: The following signatures were invalid: 062037ED98E9AE8CB5410C94A7C596C64BFE7F51
W: The repository 'https://www.valadate.org/repos/debian valadate InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by chebizarro** [comment]
Valadate is no longer maintained, thank you for your interest.
